### ISSUE TITLE
Add a License Statement to README.md

### ISSUE THREAD

**Issue by ForrestErickson** [nk25719/RobertFeranecTutorial#3]
You might look at the license on other Public Invention projects.

More generally consider developing a standard form such as:

## Summary
Brief project summary.

### Project Details
This project hardware does...
This project formware does....
Instructions....

### License and Warranty
Public Domain or....
No warranty what so ever....

**Comment by nk25719** [comment]
On my local clone I learned how to make a branch, make changes to the branch, merge it back to the main and then pushed it, using the Git bash UI.

**Comment by nk25719** [comment]
The summary is up to date.

**Comment by ForrestErickson** [comment]
Very nice.  It is much more explanatory now and forms a nice "template" or reference for future work.
